name: drupal-dev
recipe: drupal11
config:
  php: '8.3'
  webroot: web
  database: mysql:8.0
  xdebug: true
  config:
    php: .lando/php.ini

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
  composer:
    service: appserver

proxy:
  phpmyadmin:
    - pma.drupal-dev.lndo.site
